#!/bin/bash

printf "Enter image tag to turn on (enter base for base image) : "
read i1
printf "Enter container number to be (only number) : "
read i2
# printf 'Type command to run (to turn on terminal, type "/bin/bash") : '
# read i3
# i3=${i3:-"/bin/bash"}
ipaddress='192.168.128.210:5000'

if [ "$i1" = 'base' ]; then
    i1="${ipaddress}/base"
else
    i1="${SUDO_USER}:$i1"
fi

printf "image tag : $i1\n"

USER_HOME=$(getent passwd $SUDO_USER | cut -d: -f6)
USER_HOME2="/home2/${SUDO_USER}"
Public_DB='/home/Public_DB'
Public_DB2='/home2/Public_DB'
if [ -d "$USER_HOME2" ]; then 
    docker run -it --init --name "${SUDO_USER}_$i2" \
    --mount type=bind,source="$USER_HOME",target="$USER_HOME" \
    --mount type=bind,source="$USER_HOME2",target="$USER_HOME2" \
    --mount type=bind,source="$Public_DB2",target="$Public_DB",readonly \
    -e LOCAL_USER_ID="$SUDO_UID" -e LOCAL_USER_NAME="$SUDO_USER" \
    -e LOCAL_GROUP_ID="$SUDO_GID" -e LOCAL_USER_HOME="$USER_HOME" \
    --cgroup-parent=/normal_users \
    "$i1"
else
    docker run -it --init --name "${SUDO_USER}_$i2" \
    --mount type=bind,source="$USER_HOME",target="$USER_HOME" \
    --mount type=bind,source="$Public_DB2",target="$Public_DB",readonly \
    -e LOCAL_USER_ID="$SUDO_UID" -e LOCAL_USER_NAME="$SUDO_USER" \
    -e LOCAL_GROUP_ID="$SUDO_GID" -e LOCAL_USER_HOME="$USER_HOME" \
    --cgroup-parent=/normal_users \
    "$i1"
fi