FROM ubuntu:latest  

RUN apt-get update && apt-get install -y --no-install-recommends \
    make git unzip wget bzip2 xz-utils \
    openssl python3 python-pip build-essential

RUN apt-get install build-essential
