FROM ubuntu:latest  

RUN apt-get update && apt-get install -y --no-install-recommends \
    make git gcc gcc-c++ unzip wget \
    perl openssl-devel python-devel python-pip \
    java-1.8.0-openjdk ncurses-devel bzip2-devel xz-devel

RUN apt-get install build-essential